# Generated by Django 5.1.1 on 2024-11-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_is_active_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='teacher.teacher'),
        ),
    ]
